#!/usr/bin/env ruby

# -------------------------------------------------------------------------- #
# Copyright 2010-2014, C12G Labs S.L                                         #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
# -------------------------------------------------------------------------- #

$: << File.join(File.dirname(__FILE__), '../../vmm/bursting')

require 'bursting'

host     = ARGV[-1]
provider = ARGV[0]
host_id  = ARGV[4]

drv = BurstingDriver.create(provider,host)

drv.monitor_all_vms(host_id)
