#!/usr/bin/env ruby

# -------------------------------------------------------------------------- #
# Copyright 2015, Terradue S.r.l.                                            #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
# -------------------------------------------------------------------------- #

$: << File.dirname(__FILE__)

require 'opennebula'
require 'bursting'

include OpenNebula

deploy_id = ARGV[0]
host      = ARGV[1]
id        = ARGV[2]

type = ""

# Determining the bursting 'type', currently with a XML-RPC call (it is preferred
# through the ARGV arguments)
client = Client.new()

xml = client.call("vm.info", id.to_i)
xml_vm = REXML::Document.new(xml) if xml

REXML::XPath.each(xml_vm, "//PUBLIC_CLOUD/TYPE") { |e| type = e.text  }

raise "Provider type is not defined/determined" if !type.empty?

drv = BurstingDriver.create(type,host)

drv.poll(id, deploy_id)
