#!/usr/bin/env ruby

# ---------------------------------------------------------------------------- #
# Copyright 2015, Terradue S.r.l.                                              #
#                                                                              #
# Licensed under the Apache License, Version 2.0 (the "License"); you may      #
# not use this file except in compliance with the License. You may obtain      #
# a copy of the License at                                                     #
#                                                                              #
# http://www.apache.org/licenses/LICENSE-2.0                                   #
#                                                                              #
# Unless required by applicable law or agreed to in writing, software          #
# distributed under the License is distributed on an "AS IS" BASIS,            #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.     #
# See the License for the specific language governing permissions and          #
# limitations under the License.                                               #
# ---------------------------------------------------------------------------- #

$: << File.dirname(__FILE__)

require 'bursting'

dfile = ARGV[0]
host  = ARGV[1]
vm_id = ARGV[2]
type = ""

xml_text = File.read(dfile)

# Find the driver type
# (it would be preferred through the ARGV arguments)
xml = REXML::Document.new xml_text
context_xml = xml.root.get_elements("//CONTEXT")

REXML::XPath.each(context_xml, "//PUBLIC_CLOUD/TYPE") { |e| type = e.text  }
raise "Provider type is not defined/determined" if type.empty?

drv = BurstingDriver.create(type,host)

puts drv.deploy(vm_id, host, xml_text)

exit 0
