#!/usr/bin/env ruby

# -------------------------------------------------------------------------- #
# Copyright 2015, Terradue S.r.l.                                            #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
# -------------------------------------------------------------------------- #

$: << File.dirname(__FILE__)

require 'bursting'

deploy_id = ARGV[0]
host      = ARGV[1]
vm_id     = ARGV[2]

type = BurstingDriver.get_type(vm_id)

drv = BurstingDriver.create(type,host)

drv.reboot(deploy_id)
